= App rating analysis
ifdef::backend-html5[]
:toc: left
:star: ⭐
endif::[]
ifndef::backend-html5[]
:star: stars
endif::[]

List of installed games and their content rating.

== Overview

There are *{{ apps|length }}* apps analyzed here.{% if ignore %}
Apps with these ratings are not shown:
{% for i in ignore %}
* "{{ i.label }}"
{% endfor %}
{% endif %}

For more about meaning of ratings, see https://support.google.com/googleplay/answer/6209544?visit_id=638327649363597050-1150442459&p=appgame_ratings&rd=1#zippy=%2Cother-countries%2Caustralia-games-only%2Ceurope-middle-east[Apps & Games content ratings on Google Play].

{% for rating, apps_in_rating in apps|groupby("rating_order") %}
== Apps with "{{rating.label}}" rating ({{apps_in_rating|length}})
{% for app in apps_in_rating|sorted("name_order") %}
. {{app.url}}[{{app.original_name or app.name}},window=_blank] by {% if app.developer %}https://play.google.com{{ app.developer.url}}[{{ app.developer.name }},window=_blank]{% else %}n/a{% endif %}{% if app.star_rating %} ({{app.star_rating}} {star}){% endif %}{% if app.description %} -- "{{app.description}}"{% endif %} [`id={{app.play_store_id}}`]
{% endfor %}
{% endfor %}
